---
# tasks/cleanup.yml

- name: ocStore | Deploy | Clean up releases
  shell: ls -1dt {{ ocstore_www_root }}/{{ ocstore_releases_dir }}/* | tail -n +{{ ocstore_keep_releases | int + 1 }} | xargs rm -rf
  when: ocstore_keep_releases > 0
