---
# tasks/cron.yml

- name: ocStore | Deploy | Ensure cron tab jobs are exist
  cron:
    cron_file: "{{ item.file | default(omit) }}"
    user: "{{ item.user | default(lookup('env', 'USER')) }}"
    name: "{{ item.name | default(omit) }}"
    minute: "{{ item.minute | default(omit) }}"
    hour: "{{ item.hour | default(omit) }}"
    day: "{{ item.day | default(omit) }}"
    month: "{{ item.month | default(omit) }}"
    weekday: "{{ item.weekday | default(omit) }}"
    job: "{{ item.cmd | default(omit) }}"
  with_items: "{{ ocstore_cron_jobs }}"
