---
# tasks/data.yml

- name: ocStore | Deploy | Iterate over newly created databases
  include_tasks: import.yml
  when: db_item.changed and not db_item.failed
  with_items:
    - "{{ ocstore_databases_state.results }}"
  loop_control:
    loop_var: db_item
