---
# tasks/import.yml

- block:
    - name: ocStore | Deploy | Ensure database schema is up to date '{{ db_item.item.name }}'
      template: >
        src="sql/setup.sql.j2"
        dest="~/{{ db_item.item.name }}.setup.sql"
        mode="600"
    - name: ocStore | Deploy | Import database schema '{{ db_item.item.name }}'
      mysql_db:
        name: "{{ db_item.item.name }}"
        state: "import"
        target: "~/{{ db_item.item.name }}.setup.sql"
  rescue:
    - name: ocStore | Deploy | Ensure database absent '{{ db_item.item.name }}'
      mysql_db:
        name: "{{ db_item.item.name }}"
        state: "absent"
