---
# tasks/import.yml

- block:
    - name: ocStore | Deploy | Import database schema '{{ db_item.item.name }}'
      mysql_db:
        name: "{{ db_item.item.name }}"
        state: "import"
        target: "~/setup.sql"
  rescue:
    - name: ocStore | Deploy | Ensure database absent '{{ db_item.item.name }}'
      mysql_db:
        name: "{{ db_item.item.name }}"
        state: "absent"
