---
# tasks/main.yml

- import_tasks: setup.yml

- import_tasks: vhosts.yml
  become: yes

- import_tasks: databases.yml
  become: yes

- import_tasks: folders.yml
  become: yes
  when: ocstore_environment != 'development'

- import_tasks: git.yml
  when: ocstore_environment != 'development'

- import_tasks: update.yml
  become: yes
  when: ocstore_environment != 'development'
  
- import_tasks: shared.yml
  become: yes

- import_tasks: symlink.yml

- import_tasks: cleanup.yml
  when: ocstore_environment != 'development'

- import_tasks: restart.yml
  become: yes
