---
# tasks/main.yml

- import_tasks: setup.yml

- import_tasks: databases.yml
  become: yes

- import_tasks: folders.yml
  become: yes

- block:

    - import_tasks: git.yml
      when: ocstore_environment != 'development'
    
    - import_tasks: templates.yml
      become: yes
    
    - import_tasks: files.yml
      become: yes
    
    - import_tasks: symlinks.yml

    - import_tasks: permissions.yml
      when: ocstore_environment != 'development'
      become: yes
      
    - import_tasks: release.yml
    
  rescue:

    - import_tasks: rescue.yml
      when: ocstore_environment != 'development'
      become: yes

  always:

    - import_tasks: cleanup.yml
      become: yes
      when: ocstore_environment != 'development'
