---
# tasks/main.yml

- include: setup.yml

- include: vhosts.yml
  become: yes

- include: databases.yml
  become: yes

- include: folders.yml
  become: yes
  when: ocstore_environment != 'development'

- include: git.yml
  when: ocstore_environment != 'development'

- include: update.yml
  become: yes
  when: ocstore_environment != 'development'
  
- include: shared.yml
  become: yes

- include: symlink.yml

- include: cleanup.yml
  when: ocstore_environment != 'development'

- include: restart.yml
  become: yes
