---
# tasks/release.yml

- name: ocStore | Deploy | Create empty REVISION file for development environment only
  copy:
    content: ""
    dest: "{{ ocstore_current_release_dir }}/REVISION"
    mode: "660"
    group: "{{ ocstore_www_owner_group }}"
    owner: "{{ ocstore_www_owner_user }}"
  become: yes
  when: ocstore_environment == 'development'

- name: ocStore | Deploy | Ensure current symlink source is new release
  shell: ln -s "{{ ocstore_current_release_dir }}/{{ ocstore_public_dir }}" "{{ ocstore_www_root }}/{{ ocstore_current_dir }}_tmp" && mv -Tf "{{ ocstore_www_root }}/{{ ocstore_current_dir }}_tmp" "{{ ocstore_www_root }}/{{ ocstore_current_dir }}"
  args:
    warn: no

#- name: ocStore | Deploy | Ensure current symlink source is new release
#  file:
#    state: "link"
#    path: "{{ ocstore_www_root }}/{{ ocstore_current_dir }}"
#    src: "{{ ocstore_current_release_dir }}/{{ ocstore_public_dir }}"
