---
# tasks/setup.yml

- name: ocStore | Deploy | Set current release version
  set_fact:
    ocstore_current_release_version: "{{ lookup('pipe', 'date -u +%Y%m%d%H%M%SZ') }}"
  run_once: true
  when: ocstore_current_release_version is not defined

- name: ocStore | Deploy | Set current release folder
  set_fact:
    ocstore_current_release_dir: "{{ ocstore_www_root }}/{{ ocstore_public_dir if ocstore_environment == 'development' else ocstore_releases_dir + '/' + ocstore_current_release_version }}"
  when: ocstore_current_release_dir is not defined

- name: ocStore | Deploy | Get shared folder stat
  stat:
    path: "{{ ocstore_www_root }}/{{ ocstore_shared_dir }}"
  register: ocstore_shared_path
