---
# tasks/setup.yml

- name: ocStore | Deploy | Set current environment
  set_fact:
    ocstore_environment: "{{ lookup('env','ANSIBLE_ENV') | default('development') }}"
  run_once: true
  when: ocstore_environment is not defined

- name: ocStore | Deploy | Debug current environment
  debug:
    var: ocstore_environment
    verbosity: 3

- name: ocStore | Deploy | Set current release version
  set_fact:
    ocstore_current_release_version: "{{ lookup('pipe', 'date -u +%Y%m%d%H%M%SZ') }}"
  run_once: true
  when: ocstore_current_release_version is not defined

- name: ocStore | Deploy | Set current release folder
  set_fact:
    ocstore_current_release_dir: "{{ ocstore_www_root }}/{{ ocstore_public_dir if ocstore_environment == 'development' else ocstore_releases_dir + '/' + ocstore_current_release_version }}"
  when: ocstore_current_release_dir is not defined

- name: ocStore | Deploy | Get web server owner group name
  shell: "ps axo user,group,comm | egrep '(apache|httpd)' | grep -v ^root | uniq | cut -d ' ' -f 2"
  register: ocstore_www_owner_group
  run_once: true
  when: ocstore_www_owner_group is not defined

- name: ocStore | Deploy | Check web server owner group name
  fail: msg="Could not get web server owner group name!"
  when: ocstore_www_owner_group.stdout == ''
  
- name: ocStore | Deploy | Set default web server owner group name
  set_fact:
    ocstore_www_owner_group: "{{ ocstore_www_owner_group.stdout }}"
  run_once: true

- name: ocStore | Deploy | Set web server owner user name
  set_fact:
    ocstore_www_owner_user: "{{ ansible_env.USER }}"
  run_once: true
  when: ocstore_www_owner_user is not defined

- name: ocStore | Deploy | Get shared folder stat
  stat:
    path: "{{ ocstore_www_root }}/{{ ocstore_shared_dir }}"
  register: ocstore_shared_path
