---
# tasks/symlinks.yml

- name: ocStore | Deploy | Find symlinks for admin folder
  find:
    paths: "{{ ocstore_current_release_dir }}/{{ ocstore_public_dir }}"
    file_type: "link"
    patterns: "admin*"
  register: ocstore_admin_symlinks

- name: ocStore | Deploy | Ensure invalid symlinks for admin folder are absent
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "{{ ocstore_admin_symlinks.files | map(attribute='path') | list | difference([ ocstore_current_release_dir + '/' + ocstore_public_dir + '/' + ocstore_admin_dirname ]) }}"

- name: ocStore | Deploy | Ensure symlink for admin folder is present
  file:
    state: link
    path: "{{ ocstore_current_release_dir }}/{{ ocstore_public_dir }}/{{ ocstore_admin_dirname }}"
    src: "{{ ocstore_current_release_dir }}/{{ ocstore_admin_dir }}"

- name: ocStore | Deploy | Ensure symlinks for shared folders are present
  file:
    state: link
    path: "{{ ocstore_current_release_dir }}/{{ ocstore_public_dir }}/{{ item.path }}"
    src: "{{ ocstore_www_root }}/{{ ocstore_shared_dir }}/{{ item.path }}"
  with_flattened:
    - "{{ ocstore_shared_folders }}"

- name: ocStore | Deploy | Ensure symlinks for shared files are present
  file:
    state: link
    path: "{{ (item.dest[:1] == '/') | ternary(item.dest,ocstore_current_release_dir+'/'+ocstore_public_dir+'/'+item.dest) }}"
    src: "{{ ocstore_www_root }}/{{ ocstore_shared_dir }}/{{ item.path }}"
  with_flattened:
    - "{{ ocstore_shared_files }}"
