---
# tasks/templates.yml

- name: ocStore | Deploy | Ensure template files are exist in current release admin folder
  template: >
    src="admin/{{ item.path }}.j2"
    dest="{{ ocstore_current_release_dir }}/{{ ocstore_admin_dir }}/{{ item.path }}"
    group="{{ ocstore_www_owner_group }}"
    owner="{{ ocstore_www_owner_user }}"
  with_flattened:
    - "{{ ocstore_admin_template_files }}"

- name: ocStore | Deploy | Ensure template files are exist in current release public folder
  template: >
    src="{{ item.path }}.j2"
    dest="{{ ocstore_current_release_dir }}/{{ ocstore_public_dir }}/{{ item.path }}"
    group="{{ ocstore_www_owner_group }}"
    owner="{{ ocstore_www_owner_user }}"
  with_flattened:
    - "{{ ocstore_public_template_files }}"

- name: ocStore | Deploy | Ensure template files are exist in shared folder
  template: >
    src="{{ item.path }}.j2"
    dest="{{ ocstore_www_root }}/{{ ocstore_shared_dir }}/{{ item.path }}"
    group="{{ ocstore_www_owner_group }}"
    owner="{{ ocstore_www_owner_user }}"
  with_flattened:
    - "{{ ocstore_shared_template_files }}"
