---
# tasks/update.yml

- name: ocStore | Deploy | Copy current release version into REVISION file
  copy:
    content: "{{ ocstore_current_release_version }}"
    dest: "{{ ocstore_current_release_dir }}/REVISION"
    group: "{{ ocstore_www_owner_user }}"
    owner: "{{ ocstore_www_owner_user }}"
    mode: "600"
